### ISSUE TITLE
Error when trashing file in version 2.0.0 and 2.0.1

### ISSUE THREAD

**Issue by weclaw1** [ArturKovacs/trash-rs#30]
When I try to move to trash a file on Fedora 34 I get the following error: Error during a `trash` operation: Unknown { description: "Path: '\"/home/.Trash-1000\"'. Message: Permission denied (os error 13)" }
When I use the 1.3.0 version of this library everything works correctly.

**Comment by ArturKovacs** [comment]
Could you run the same with the `RUST_LOG` env var set to `debug`. If I'm not mistaken if you execute your program like the following, it should print the log to the stderr or maybe the stdout:
```
RUST_LOG=debug ./my_program
```

**Comment by ArturKovacs** [comment]
Oh and thanks for reporting this!

**Comment by weclaw1** [comment]
I ran it with debug, I didn't show too much but here is the log:
```
[2021-08-08T20:54:44Z DEBUG trash::platform] Deleting "/home/weclaw/Obrazy/Dron(kopia)/20210322_154901_0001.JPG"
[2021-08-08T20:54:44Z DEBUG trash::platform] The topdir of this file is "/home"
[2021-08-08T20:54:44Z ERROR image_roll::app] ERROR: Error during a `trash` operation: Unknown { description: "Path: '\"/home/.Trash-1000\"'. Message: Permission denied (os error 13)" }
```

**Comment by ArturKovacs** [comment]
I'm seeing now that my mistake is probably that I assume that the partition of the home trash is always mounted at the root. But obviously this is not correct. (In this case the home partition seems to be mounted at "/home")

I think this is the culprit: https://github.com/ArturKovacs/trash-rs/blob/2a1eaf8630b2c49b06e28d323d85e95dd0dd514a/src/freedesktop.rs#L51-L59

**Comment by ArturKovacs** [comment]
The correct way of doing this would be to check if the `topdir` is identical to the topdir of the `home_trash`.

**Comment by weclaw1** [comment]
Fedora creates a separate home partition mounted on /home by default, so you are most likely right.

**Comment by ArturKovacs** [comment]
@weclaw1 could you test with #34 and see if this still happens?

**Comment by weclaw1** [comment]
I have tested with the issue-30 branch in #34 and it fixes this bug :)

**Comment by ArturKovacs** [comment]
The new version with the fix is now published
