### ISSUE TITLE
Test failed on fedora copr

### ISSUE THREAD

**Issue by remilauzier** [ArturKovacs/trash-rs#31]
https://download.copr.fedorainfracloud.org/results/remilauzier/trash/fedora-rawhide-x86_64/02450898-rust-trash/builder-live.log.gz

failures:

---- platform::tests::test_list stdout ----
thread 'platform::tests::test_list' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown { description: "No such file or directory (os error 2)" }', src/freedesktop.rs:650:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    platform::tests::test_list

test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

**Comment by ArturKovacs** [comment]
I'd like to ask you to try #35 by running the following and then pasting the output of the run here.
```
RUST_LOG=warn cargo test -- --nocapture
```

**Comment by remilauzier** [comment]
Sadly, this is way above what copr can do.

**Comment by ArturKovacs** [comment]
Alright we gonna do it the manual way. I just merged the PR and I'm going to make a release soon. If it's still broken after the release, feel free to reopen this issue.
