### ISSUE TITLE
Doctest failed on aarch64

### ISSUE THREAD

**Issue by remilauzier** [ArturKovacs/trash-rs#32]
https://download.copr.fedorainfracloud.org/results/remilauzier/trash/fedora-rawhide-aarch64/02451115-rust-trash/builder-live.log.gz

failures:

---- src/lib.rs - os_limited::list (line 314) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown { description: "Path: '\"/builddir/.local/share/Trash/info\"'. Message: No such file or directory (os error 2)" }', src/lib.rs:5:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    src/lib.rs - os_limited::list (line 314)

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.86s

**Comment by ArturKovacs** [comment]
#36 should fix this issue. Please test it if you can, or let me know if you can't. Thanks!

**Comment by remilauzier** [comment]
I won't be able to test it since i don't have a aarch64 machine at disposition. I can only test it when the code is release on crates.io since that where fedora take the source.

**Comment by remilauzier** [comment]
Testing pr is way above what copr can do sadly.

**Comment by ArturKovacs** [comment]
The new version with the fix is now published
